name: greengrocer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.2
  mask_text_input_formatter: ^2.9.0
  badges: ^3.1.2
  intl: ^0.19.0
  add_to_cart_animation: ^0.0.7
  fluttertoast: ^8.2.6
  shimmer: ^3.0.0
  get: ^4.6.6
  dio: ^5.6.0
  json_annotation: ^4.9.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/fruits/
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_images/app_icon.png"
  remove_alpha_ios: true
